# inherit_from: .rubocop_todo.yml
# AllCops:
#   Include:
#     - Rakefile
#     - config.ru
#     - lib/**/*.rake
#   Exclude:
#     - db/schema.rb
# inherit_from:
# - https://relaxed.ruby.style/rubocop.yml
# inherit_gem:
#   relaxed-rubocop: .rubocop.yml

inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'

Rails:
  Enabled: True

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'
