inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
inherit_from:
- https://relaxed.ruby.style/rubocop.yml
inherit_gem:
  relaxed-rubocop: .rubocop.yml